################################
#
# ELOC 数据源配置
#
################################

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://130.3.3.38:3306/eloc1?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8'
    username: eloc1
    password: '{cipher}a8bca389876c47817d42714ae91ce908cde2c6333ce52b73fcd5c980edc70293'
  druid:
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: 'SELECT 1 FROM DUAL'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
  redis:
    host: 130.3.3.24
    port: 6379
    timeout: 5000
    password: '{cipher}a8bca389876c47817d42714ae91ce908cde2c6333ce52b73fcd5c980edc70293'
